title: asinkLuno
subtitle:
description:
author: asinkLuno
language: zh-CN
timezone: Asia/Shanghai

url: https://asinkluno.github.io/asinkLuno
root: /asinkLuno/
permalink: :year/:month/:day/:title/
per_page: 20

category_map:
  HN复读机: hn
  摇滚大陆漫游记: manyuki
  最低生存烹饪指南: survival-cooking
  您是完全不读书吗: reading

theme: minima

deploy:
  type:
