hexo.extend.injector.register(
  "body_end",
  `<script src="https://giscus.app/client.js"
    data-repo="asinkLuno/asinkLuno"
    data-repo-id="R_kgDOQoBHOw"
    data-category="Announcements"
    data-category-id="DIC_kwDOQoBHO84DCMos"
    data-mapping="title"
    data-strict="1"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="bottom"
    data-theme="preferred_color_scheme"
    data-lang="zh-CN"
    data-loading="lazy"
    crossorigin="anonymous"
    async></script>`,
  "post",
);
